name: Build npm release

trigger:
  - master

jobs:
  - template: .ci/build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-16.04
      esyLockPath: $(Build.SourcesDirectory)/esy.lock/index.json
      ESY__PREFIX: $(Pipeline.Workspace)/.esy

  - template: .ci/build-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-10.13
      esyLockPath: $(Build.SourcesDirectory)/esy.lock/index.json
      ESY__PREFIX: $(Pipeline.Workspace)/.esy

#  - template: .ci/build-platform.yml
#    parameters:
#      platform: Windows
#      vmImage: vs2017-win2016
#      esyLockPath: $(Build.SourcesDirectory)\esy.lock\index.json
#      ESY__PREFIX: $(Pipeline.Workspace)\.esy
