parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"
  esyLockPath: $(Build.SourcesDirectory)/esy.lock
  ESY__PREFIX: $(Pipeline.Workspace)/.esy

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      ESY__PREFIX: ${{ parameters.ESY__PREFIX }}

    steps:
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - task: CacheBeta@0
        displayName: Cache esy
        inputs:
          key: esy | $(Agent.OS) | ${{ parameters.esyLockPath }}
          path: $(ESY__PREFIX)
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      - template: utils/create-docs.yml
      - script: "esy test"
        displayName: "Test command"
