parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"
  esyLockPath: $(Build.SourcesDirectory)/esy.lock
  installFolderPath: /3_______________________________________________
  ESY__PREFIX: $(Pipeline.Workspace)/.esy

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      ESY__PREFIX: ${{ parameters.ESY__PREFIX }}

    steps:
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - task: CacheBeta@0
        displayName: Cache esy
        inputs:
          key: $(Agent.OS) | esy | ${{ parameters.esyLockPath }}
          path: ${{ parameters.ESY__PREFIX }}${{ parameters.installFolderPath }}
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      - template: utils/create-docs.yml
      - script: "esy test"
        displayName: "Test command"
      - script: echo '${{ parameters.ESY__PREFIX }}${{ parameters.installFolderPath }}'
      - script: ls ${{ parameters.ESY__PREFIX }}
